disableKinds = ["home"]

baseURL = "https://padiemai.netlify.app/"
languageCode = "ko"
title = "파디엠 블로그"
theme = "PaperMod"
defaultContentLanguage = "ko"
pagination.pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[params]
  homeInfoParams = { Title = "파디엠 블로그", Content = "AI, 기술, 회사 소식, 연구 등 다양한 이야기를 전합니다." }
  description = "파디엠 공식 블로그"
  author = "Padiem AI"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  ShowLastMod = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowSocialIcons = true
  ShowLightDarkMode = true
  defaultTheme = "auto" # 다크/라이트 자동
  comments = false
  disableScrollToTop = false
  disableSpecial1stPost = false
  disableAnchoredHeadings = false
  env = "production"
  keywords = ["AI", "파디엠", "인공지능", "기업AI", "성공사례", "교육AI", "금융AI", "보안AI"]
  images = ["/images/index/ipu.jpg"]
  # SEO/OG
  ogImage = "/images/index/ipu.jpg"
  twitterCard = "summary_large_image"
  # 검색
  fuseOpts = { isCaseSensitive = false, shouldSort = true, includeMatches = true, findAllMatches = true, minMatchCharLength = 2, location = 0, threshold = 0.3, distance = 100, useExtendedSearch = true, ignoreLocation = true, includeScore = true }
  # 접근성
  accessibility = true

[languages]
  [languages.ko]
    languageName = "한국어"
    weight = 1
    contentDir = "content"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[[menu.main]]
  name = "홈"
  url = "/"
  weight = 1

[[menu.main]]
  name = "회사소개"
  url = "/company/"
  weight = 2

[[menu.main]]
  name = "정보"
  url = "/information/"
  weight = 3

[[menu.main]]
  name = "블로그"
  url = "/posts/"
  weight = 4

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/padiemai"
[[params.socialIcons]]
  name = "email"
  url = "mailto:info@padiem.net"
