[build]
  publish = "public"
  command = "hugo && cp static/index.html public/index.html"

[[ignore_files]]
  files = [
    "hugo.zip",
    "logs/*",
    "tests/*",
    "blog_old/*",
    "temp_files.txt",
    "temp_tree.txt",
    "tree.md"
  ] 